### ISSUE TITLE
Add `removable-media` permission to the package

### ISSUE THREAD

**Issue by SylvainBigonneau** [anrouxel/godot-engine-snapcraft#5]
First of all, thank you for setting up this up-to-date snap for Godot !

I work on my games from different computers on different OSes, and therefore really need to be able to access my projects on my external hard drive.

Could it be possible to add the `removable-media` permission option so I can enable it? Thanks!

**Comment by anrouxel** [comment]
Hi @SylvainBigonneau ,
I added `removable-media` and `joystick` permission to the package. `removable-media` should solve your problem and will allow you to access removable media. And I added `joystick` that should support joysticks.
Best Regards

**Comment by SylvainBigonneau** [comment]
Thank you for the fast and efficient fix, it works perfectly!
